[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "torch>=2.5.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
